### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by frankcash** [srqsoftware/03-25-2015_Docker-Its_My_Code_in_a_Box#1]
`apt-get update` only updates the source list to truly update you need to run `apt-get upgrade`

**Comment by tdc9998** [comment]
yeah, good point. Could I ask a favor of you? I've never worked with a pull request before, so could you propose the change and send me a pull request? It's not critical, but it would be nice to give it a try. Let me know what you think.

**Comment by frankcash** [comment]
Will get to it this afternoon :facepunch:
